name: vernet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.13.4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Helps implement the BLoC pattern.
  bloc: ^8.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  dart_ping: ^7.0.1
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.0.1
  # Annotations for freezed
  freezed_annotation: ^1.1.0
  # Service locator
  get_it: ^7.2.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.4
  # Convenient code generator for get_it
  injectable: ^1.5.3
  # An easy way to create a new isolate, keep it running and communicate with it.
  isolate_contactor: ^1.2.0+1
  # Discover network info and configure themselves accordingly
  network_info_plus: ^2.1.2
  # Helps you discover open ports, devices on subnet and more.
  network_tools: ^3.0.0+2
  # network_tools: 
  #   git: https://github.com/git-elliot/network_tools.git
  # Querying information about the application package, such as CFBundleVersion
  package_info_plus: ^1.3.0
  # Allows you to display progress widgets based on percentage.
  percent_indicator: ^4.0.0
  # Popup that ask for the requested permission
  permission_handler: ^8.3.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.2
  # Reading and writing simple key-value pairs
  shared_preferences: ^2.0.13
  # Plugin for launching a URL
  url_launcher: ^6.0.20

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^1.1.1
  # Convenient code generator for get_it.
  injectable_generator: ^1.5.3
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ports_lists.json
    - secrets.json
    - ipwhois.json
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
