name: vernet
description: A new Flutter project.

publish_to: 'none'

version: 0.14.0

environment:
  sdk: ">=2.17.0 <3.0.0"

flutter:
  uses-material-design: true

  assets:
    - ports_lists.json
    - secrets.json
    - ipwhois.json

dependencies:
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Helps implement the BLoC pattern.
  bloc: ^8.0.3
  # Default icons asset for Cupertino.
  cupertino_icons: ^1.0.5
  # Multi-platform network ping utility.
  dart_ping: ^6.1.1
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget.
  flutter_bloc: ^8.0.1
  # Annotations for freezed.
  freezed_annotation: ^2.1.0
  # Service locator.
  get_it: ^7.2.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.4
  # Convenient code generator for get_it.
  injectable: ^1.5.3
  # An easy way to create a new isolate, keep it running and communicate with it.
  isolate_contactor: ^2.0.0
  # Discover network info and configure themselves accordingly.
  network_info_plus: ^2.1.3
  # Helps you discover open ports, devices on subnet and more.
  network_tools: ^1.0.8
  # Querying information about the application package, such as CFBundleVersion.
  package_info_plus: ^1.4.2
  # Allows you to display progress widgets based on percentage.
  percent_indicator: ^4.2.2
  # Popup that ask for the requested permission.
  permission_handler: ^10.0.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.3
  # Reading and writing simple key-value pairs.
  shared_preferences: ^2.0.15
  # Plugin for launching a URL.
  url_launcher: ^6.1.5

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # Testing library for flutter.
  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.1.0+1
  # Convenient code generator for get_it.
  injectable_generator: ^1.5.4
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.2
